const products = {
  'express-station-410': {
    name: 'Oracle MICROS Express Station 410', image: 'assets/products/express-station-410.png',
    category: {en:'All-in-one point of sale',ar:'محطة نقاط بيع متكاملة'},
    summary: {en:'A wide-format, fixed POS station engineered for hotel and restaurant counters where performance, clarity and a clean footprint matter.',ar:'محطة نقاط بيع ثابتة بشاشة عريضة، مصممة لكونترات الفنادق والمطاعم التي تتطلب الأداء والوضوح والتصميم المدمج.'},
    description: {en:'The Express Station 410 combines a 23.8-inch touch display, quad-core Intel processing and flexible peripheral connectivity in a fanless enclosure. It is a strong fit for busy service points, self-service applications and guest-facing workflows.',ar:'تجمع Express Station 410 بين شاشة لمس مقاس 23.8 بوصة ومعالجة إنتل رباعية النواة واتصال مرن بالملحقات ضمن هيكل بلا مروحة. وهي مناسبة لنقاط الخدمة المزدحمة وتطبيقات الخدمة الذاتية وتجارب الضيوف.'},
    features:{en:['Large, high-clarity touchscreen','Fanless construction for quiet operation','Flexible USB and serial peripheral connectivity','Optional magnetic-stripe reader, fingerprint reader and sound bar','Operating range suitable for demanding service environments'],ar:['شاشة لمس كبيرة وعالية الوضوح','تصميم بلا مروحة لتشغيل هادئ','اتصال مرن عبر منافذ USB وSerial','خيارات لقارئ البطاقات والبصمة والشريط الصوتي','نطاق تشغيل مناسب لبيئات الخدمة المتطلبة']},
    specs:{en:[['Processor','Intel Atom x5 quad-core'],['Memory','8 GB RAM'],['Storage','128 GB SSD'],['Display','23.8-inch HD touchscreen'],['Operating system','Windows 10 IoT / Oracle Linux'],['Ports','5× USB, 2× Serial, Gigabit Ethernet'],['Dimensions','561 × 340 × 61 mm'],['Weight','Approx. 5.9 kg'],['Power','85–264 V / C13']],ar:[['المعالج','Intel Atom x5 رباعي النواة'],['الذاكرة','8 جيجابايت RAM'],['التخزين','128 جيجابايت SSD'],['الشاشة','شاشة لمس HD مقاس 23.8 بوصة'],['نظام التشغيل','Windows 10 IoT / Oracle Linux'],['المنافذ','5× USB، 2× Serial، إيثرنت جيجابت'],['الأبعاد','561 × 340 × 61 مم'],['الوزن','حوالي 5.9 كجم'],['الطاقة','85–264 فولت / C13']]}
  },
  'workstation-820-low': {
    name:'Oracle MICROS Workstation 820 — Low Stand',image:'assets/products/workstation-820-low.png',category:{en:'Counter workstation',ar:'محطة عمل للكاونتر'},summary:{en:'A compact 14-inch FHD touchscreen workstation with a low-profile stand and integrated customer display.',ar:'محطة عمل مدمجة بشاشة لمس FHD مقاس 14 بوصة وحامل منخفض وشاشة عميل مدمجة.'},description:{en:'Built for contemporary hospitality counters, the Workstation 820 balances a slim footprint with Windows 11 IoT performance and practical expansion options. The low stand keeps the interaction comfortable for staff and guests.',ar:'صممت Workstation 820 لكونترات الضيافة الحديثة، وتجمع بين الحجم النحيف وأداء Windows 11 IoT وخيارات التوسعة العملية، مع حامل منخفض يوفر تفاعلاً مريحاً للموظفين والضيوف.'},features:{en:['Anti-glare on-cell FHD touchscreen','Quad-core Intel performance with 8 GB memory','Integrated customer-facing display','Optional port expansion for complex installations','Lightweight, refined counter design'],ar:['شاشة لمس FHD مانعة للانعكاس','أداء إنتل رباعي النواة مع ذاكرة 8 جيجابايت','شاشة مدمجة موجهة للعميل','توسعة منافذ اختيارية للتركيبات المتقدمة','تصميم أنيق وخفيف للكاونتر']},specs:{en:[['Processor','Intel Celeron J6413 quad-core'],['Memory','8 GB RAM'],['Storage','256 GB SSD'],['Display','14-inch FHD 1920×1080 touch'],['Operating system','Windows 11 IoT LTSC 2024'],['Connectivity','Ethernet; optional Wi-Fi 6E'],['Weight','1.09 kg'],['Dimensions with stand','329 × 100 × 296 mm']],ar:[['المعالج','Intel Celeron J6413 رباعي النواة'],['الذاكرة','8 جيجابايت RAM'],['التخزين','256 جيجابايت SSD'],['الشاشة','شاشة لمس FHD مقاس 14 بوصة بدقة 1920×1080'],['نظام التشغيل','Windows 11 IoT LTSC 2024'],['الاتصال','إيثرنت؛ Wi-Fi 6E اختياري'],['الوزن','1.09 كجم'],['الأبعاد مع الحامل','329 × 100 × 296 مم']]}
  },
  'workstation-820-vertical': {
    name:'Oracle MICROS Workstation 820 — Vertical Stand',image:'assets/products/workstation-820-vertical.png',category:{en:'Space-saving point of sale',ar:'نقطة بيع موفرة للمساحة'},summary:{en:'The performance of the Workstation 820 in a fixed-angle vertical format that frees valuable counter space.',ar:'أداء Workstation 820 ضمن تصميم عمودي ثابت الزاوية يوفر مساحة قيمة على الكاونتر.'},description:{en:'This configuration offers the same responsive touchscreen and reliable Windows IoT platform as the low-stand model, while its vertical footprint suits tighter service counters and visually streamlined installations.',ar:'يوفر هذا التكوين شاشة اللمس السريعة ومنصة Windows IoT الموثوقة نفسها، بينما يناسب تصميمه العمودي كونترات الخدمة الضيقة والتركيبات ذات المظهر الانسيابي.'},features:{en:['Space-efficient vertical footprint','Fixed viewing angle for consistent ergonomics','14-inch FHD on-cell touchscreen','Quad-core processing and SSD storage','Lightweight all-in-one construction'],ar:['تصميم عمودي موفر للمساحة','زاوية عرض ثابتة ومريحة','شاشة لمس FHD مقاس 14 بوصة','معالجة رباعية النواة وتخزين SSD','هيكل متكامل وخفيف الوزن']},specs:{en:[['Processor','Intel Celeron J6413 quad-core'],['Memory','8 GB RAM'],['Storage','256 GB SSD'],['Display','14-inch FHD 1920×1080 touch'],['Operating system','Windows 11 IoT LTSC 2024'],['Weight','1.09 kg'],['Dimensions with stand','329 × 289 × 182 mm']],ar:[['المعالج','Intel Celeron J6413 رباعي النواة'],['الذاكرة','8 جيجابايت RAM'],['التخزين','256 جيجابايت SSD'],['الشاشة','شاشة لمس FHD مقاس 14 بوصة بدقة 1920×1080'],['نظام التشغيل','Windows 11 IoT LTSC 2024'],['الوزن','1.09 كجم'],['الأبعاد مع الحامل','329 × 289 × 182 مم']]}
  },
  'tablet-722p': {
    name:'Oracle MICROS Tablet 722P',image:'assets/products/tablet-722p.png',category:{en:'Mobile ordering and payment',ar:'الطلب والدفع المتنقل'},summary:{en:'A purpose-built 7-inch hospitality tablet for tableside ordering, barcode scanning and contactless interactions.',ar:'جهاز لوحي للضيافة مقاس 7 بوصات مخصص للطلب عند الطاولة ومسح الباركود والتعاملات اللاتلامسية.'},description:{en:'The Tablet 722P gives service teams a compact mobile workstation with integrated scanning, NFC, camera and a replaceable battery. Hot-swap capability helps operations continue through long shifts without taking the device out of service.',ar:'يمنح Tablet 722P فرق الخدمة محطة عمل متنقلة ومدمجة مزودة بالمسح وNFC والكاميرا وبطارية قابلة للاستبدال. وتساعد ميزة التبديل السريع على استمرار العمل طوال الورديات الطويلة.'},features:{en:['Integrated 2D barcode scanner','NFC for contactless workflows','Rear camera and magnetic-stripe reader','Hot-swappable battery for continuous operation','Mounting points for payment device and shoulder strap'],ar:['ماسح باركود ثنائي الأبعاد مدمج','NFC للعمليات اللاتلامسية','كاميرا خلفية وقارئ بطاقات ممغنطة','بطارية قابلة للتبديل السريع','نقاط تثبيت لجهاز الدفع وحزام الكتف']},specs:{en:[['Display','7-inch touchscreen'],['Memory','4 GB RAM'],['Storage','128 GB'],['Operating system','Windows 10 IoT Enterprise 2021 LTSC'],['Scanner','Integrated 2D barcode'],['Contactless','NFC'],['Camera','Rear-facing'],['Ports','High-speed USB, 12 V port, 3.5 mm jack'],['Battery','Replaceable lithium battery']],ar:[['الشاشة','شاشة لمس 7 بوصات'],['الذاكرة','4 جيجابايت RAM'],['التخزين','128 جيجابايت'],['نظام التشغيل','Windows 10 IoT Enterprise 2021 LTSC'],['الماسح','باركود ثنائي الأبعاد مدمج'],['الاتصال اللاتلامسي','NFC'],['الكاميرا','خلفية'],['المنافذ','USB عالي السرعة، منفذ 12V، مقبس 3.5 مم'],['البطارية','ليثيوم قابلة للاستبدال']]}
  },
  'epson-tm-t88vi': {
    name:'Epson TM-T88VI',image:'assets/products/epson-tm-t88vi.png',category:{en:'High-speed thermal printing',ar:'طباعة حرارية عالية السرعة'},summary:{en:'An industry-standard receipt printer combining speed, reliability and flexible network and cloud printing.',ar:'طابعة فواتير بمعيار صناعي تجمع بين السرعة والموثوقية والطباعة المرنة عبر الشبكة والسحابة.'},description:{en:'The TM-T88VI is designed for demanding checkout environments. Fast output, easy paper loading, automatic cutting and versatile interfaces help reduce transaction time while supporting modern server and cloud-based POS architectures.',ar:'صممت TM-T88VI لبيئات الدفع المتطلبة. وتساعد سرعة الطباعة وسهولة تحميل الورق والقص التلقائي والواجهات المتعددة على تقليل زمن المعاملة ودعم أنظمة نقاط البيع الحديثة.'},features:{en:['Print speed up to 350 mm/s','Drop-in paper loading and automatic cutter','True grayscale text and graphics','ePOS-Print and server/cloud printing support','Printhead life of approximately 70 million lines'],ar:['سرعة طباعة تصل إلى 350 مم/ث','تحميل ورق سهل وقاطع تلقائي','طباعة نصوص ورسومات بتدرج رمادي حقيقي','دعم ePOS-Print والطباعة من الخوادم والسحابة','عمر رأس طباعة يقارب 70 مليون سطر']},specs:{en:[['Print method','Direct thermal'],['Resolution','180 × 180 dpi'],['Paper width','80 mm or 58 mm'],['Speed','Up to 350 mm/s'],['Interfaces','USB, Ethernet and Serial; optional NFC'],['Cutter','Automatic'],['Dimensions','Approx. 145 × 199 × 148 mm'],['Weight','Approx. 1.7 kg']],ar:[['طريقة الطباعة','حرارية مباشرة'],['الدقة','180 × 180 dpi'],['عرض الورق','80 مم أو 58 مم'],['السرعة','حتى 350 مم/ث'],['الواجهات','USB وإيثرنت وSerial؛ NFC اختياري'],['القاطع','تلقائي'],['الأبعاد','حوالي 145 × 199 × 148 مم'],['الوزن','حوالي 1.7 كجم']]}
  },
  'cash-drawer': {
    name:'APG Vasario 1616',image:'assets/products/cash-drawer.png',category:{en:'Secure cash management',ar:'إدارة نقد آمنة'},summary:{en:'A durable 16 × 16-inch cash drawer with configurable tills, dual media slots and printer-driven operation.',ar:'درج نقود متين مقاس 16 × 16 بوصة مع خانات قابلة للتخصيص وفتحتي وسائط وتشغيل عبر الطابعة.'},description:{en:'The Vasario 1616 is a practical hospitality cash drawer built for frequent daily transactions. Its robust enclosure, multifunction lock and configurable till support dependable cash handling across restaurant and hotel outlets.',ar:'يعد Vasario 1616 درج نقود عملياً لقطاع الضيافة ومصمماً للمعاملات اليومية المتكررة. ويدعم هيكله المتين وقفله متعدد الوظائف وخاناته القابلة للتخصيص إدارة نقد موثوقة.'},features:{en:['Five bill and five coin compartments','Printer-driven opening','Multifunction lock and drawer-status reporting','Two media slots','Durable metal construction'],ar:['خمس خانات أوراق وخمس خانات عملات','فتح عبر الطابعة','قفل متعدد الوظائف وتقرير حالة الدرج','فتحتا وسائط','هيكل معدني متين']},specs:{en:[['Dimensions','16.2 × 16.3 × 4.3 inches'],['Till','5 bill / 5 coin'],['Interface','Printer, Serial or USB'],['Construction','Metal and plastic'],['Media slots','Two'],['Models','VB320 / VB554A-BL1616']],ar:[['الأبعاد','16.2 × 16.3 × 4.3 بوصة'],['الخانات','5 أوراق / 5 عملات'],['الواجهة','طابعة أو Serial أو USB'],['البنية','معدن وبلاستيك'],['فتحات الوسائط','فتحتان'],['الموديلات','VB320 / VB554A-BL1616']]}
  },
  'battery-charger': {
    name:'4-Bay Battery Charger',image:'assets/products/battery-charger.png',category:{en:'Operational continuity',ar:'استمرارية التشغيل'},summary:{en:'A dedicated four-bay charger that keeps spare Oracle MICROS Tablet 700 batteries ready for uninterrupted service.',ar:'شاحن مخصص بأربعة منافذ يحافظ على جاهزية بطاريات Oracle MICROS Tablet 700 الاحتياطية لاستمرار الخدمة.'},description:{en:'Designed for busy mobile service teams, this desktop charger replenishes four batteries at once. Individual status indicators make it easy to manage charged inventory throughout each shift.',ar:'صمم هذا الشاحن المكتبي لفرق الخدمة المتنقلة المزدحمة، ويشحن أربع بطاريات في وقت واحد. وتسهّل مؤشرات الحالة الفردية إدارة البطاريات الجاهزة طوال الوردية.'},features:{en:['Charges four batteries simultaneously','Individual charging-status indicators','Compact desktop footprint','External 12 V power adapter','Purpose-built for Tablet 700 batteries'],ar:['شحن أربع بطاريات في الوقت نفسه','مؤشر حالة لكل منفذ','حجم مكتبي مدمج','محول طاقة خارجي 12 فولت','مخصص لبطاريات Tablet 700']},specs:{en:[['Charging bays','Four'],['Power','External 12 V DC / C13'],['Dimensions','Approx. 185 × 162 × 54 mm'],['Compatibility','Oracle MICROS Tablet 700 batteries'],['Item number','7118826']],ar:[['منافذ الشحن','أربعة'],['الطاقة','محول خارجي 12V DC / C13'],['الأبعاد','حوالي 185 × 162 × 54 مم'],['التوافق','بطاريات Oracle MICROS Tablet 700'],['رقم الصنف','7118826']]}
  },
  'tablet-battery': {
    name:'Tablet 700 Li‑Polymer Battery',image:'assets/products/tablet-battery.png',category:{en:'Replaceable mobile power',ar:'طاقة متنقلة قابلة للاستبدال'},summary:{en:'A lightweight replacement battery that supports continuous Tablet 700 operation through fast battery swaps.',ar:'بطارية بديلة خفيفة تدعم التشغيل المتواصل لجهاز Tablet 700 عبر التبديل السريع.'},description:{en:'Keeping charged spare batteries on hand helps mobile service teams avoid device downtime. This lithium-polymer pack is designed for the Oracle MICROS Tablet 700 family and works with the four-bay charging system.',ar:'يساعد توفر بطاريات احتياطية مشحونة فرق الخدمة المتنقلة على تجنب توقف الأجهزة. صممت بطارية الليثيوم بوليمر هذه لعائلة Oracle MICROS Tablet 700 وتتوافق مع نظام الشحن رباعي المنافذ.'},features:{en:['Fast field replacement','Lightweight lithium-polymer construction','Designed for extended mobile operation','Compatible with the four-bay charger','Supports uninterrupted service workflows'],ar:['استبدال سريع أثناء العمل','تركيب خفيف من الليثيوم بوليمر','مصممة للتشغيل المتنقل الممتد','متوافقة مع الشاحن رباعي المنافذ','تدعم استمرارية عمليات الخدمة']},specs:{en:[['Chemistry','Lithium polymer'],['Nominal voltage','Approx. 3.7 V'],['Compatibility','Oracle MICROS Tablet 700'],['Item number','7601701']],ar:[['النوع','ليثيوم بوليمر'],['الجهد الاسمي','حوالي 3.7 فولت'],['التوافق','Oracle MICROS Tablet 700'],['رقم الصنف','7601701']]}
  }
};

const html = document.documentElement;
const languageToggle = document.querySelector('#languageToggle');
const key = new URLSearchParams(location.search).get('id');
const product = products[key] || products['express-station-410'];

function render(language) {
  const arabic = language === 'ar';
  html.lang = language; html.dir = arabic ? 'rtl' : 'ltr';
  document.body.classList.toggle('is-arabic', arabic);
  document.querySelectorAll('[data-en][data-ar]').forEach(node => node.textContent = node.dataset[language]);
  languageToggle.textContent = arabic ? 'English' : 'العربية';
  languageToggle.setAttribute('aria-label', arabic ? 'Switch to English' : 'التبديل إلى العربية');
  productCategory.textContent = product.category[language]; productName.textContent = product.name;
  productSummary.textContent = product.summary[language]; productDescription.textContent = product.description[language];
  productImage.src = product.image; productImage.alt = product.name;
  productFeatures.replaceChildren(...product.features[language].map(text => { const li=document.createElement('li'); li.textContent=text; return li; }));
  productSpecs.replaceChildren(...product.specs[language].flatMap(([label,value]) => { const dt=document.createElement('dt'); dt.textContent=label; const dd=document.createElement('dd'); dd.textContent=value; return [dt,dd]; }));
  const subject = encodeURIComponent(`${arabic ? 'طلب عرض سعر' : 'Quotation request'} — ${product.name}`);
  quoteLink.href = bottomQuoteLink.href = `mailto:oshammari@asftech.net?subject=${subject}`;
  document.title = `${product.name} | ASF Information Technology`;
  localStorage.setItem('asf-language', language);
}

languageToggle.addEventListener('click', () => render(html.lang === 'ar' ? 'en' : 'ar'));
document.querySelector('#year').textContent = new Date().getFullYear();
render(localStorage.getItem('asf-language') === 'ar' ? 'ar' : 'en');
